### ISSUE TITLE
HHL

### ISSUE THREAD

**Issue by HuJianbing** [savrus/hl#1]
Dear savrus:
     I am a student who are learning HHL and find your code very useful. However, I found I have some difficulties in understanding the file <<hhl.hpp>>. I notice that there is a sentence:
  assert(cover_size[w] == 0 && sp_size[w] == 0).
However, during our implementation, we found sp_size[w] == 0 can not be ensured. We think the reason might be the function get_descendants(), where a check:
 if (!visited[a->head] && !get_cover(u,a->head,forward) && is_path(u,d[i],a->head,a->length,forward)) 
will skip the search of covered descendants of v when u=v previously. Can you help us in understanding this issue? Your kind assistance will help us a lot.

**Comment by HuJianbing** [comment]
Hello, during our test, I found what I understand wrong. Feel sorry for disturbing you.

**Comment by savrus** [comment]
No problem :)
