### ISSUE TITLE
Performance compared to Akiba paper

### ISSUE THREAD

**Issue by bkj** [savrus/hl#3]
I'm running `./akiba` on some of the datasets benchmarked in the original paper.  Performance of this code appears slower than the numbers they were quoting:

```
notre dame - 4.5s in original - 26 seconds in this code (5.7x slowdown)
Gnutella21 - 54s in original - 3m13s in this code (3.5x slowdown)
```

Do you have any idea where the performance gap might be coming from?  Also, do you know if there's a link to the original Akiba implementation somewhere?

Thanks!
~ Ben

**Comment by savrus** [comment]
Original implementation is more advanced algorithm than the one implemented here. If I remember correctly they use some bitwise-level hardware parallelism, so I'm not surprised.

**Comment by bkj** [comment]
OK -- makes sense, thanks for the explanation.

For posterity, the original code is here: https://github.com/iwiwi/pruned-landmark-labeling
